#!/bin/sh
# Synth3x Console — Help & Commands
echo ""
echo " ══════════════════════════════════════════════════════════"
echo "   SYNTH3X CONSOLE v0.8.1 — COMMAND REFERENCE"
echo " ══════════════════════════════════════════════════════════"
echo ""
echo "  INSTALLATION:"
echo "    synth3x-installer     Start the 10-step terminal installer"
echo ""
echo "  NETWORK:"
echo "    synth3x-wifi          WiFi scan, connect, disconnect"
echo "    iwctl                 WiFi config (interactive)"
echo "    iw                    Wireless tools"
echo "    ping <host>           Test network connectivity"
echo "    wget <url>            Download files"
echo ""
echo "  PACKAGE MANAGEMENT (after installation):"
echo "    emerge --ask <pkg>    Install a Gentoo package"
echo "    emerge --sync         Update Portage tree"
echo "    emerge -uDN @world    Update all packages"
echo ""
echo "  DISK & PARTITIONS:"
echo "    parted /dev/sdX       Partition editor"
echo "    lsblk                 Show block devices"
echo "    fdisk -l              List partitions"
echo ""
echo "  DESKTOP ENVIRONMENT:"
echo "    synth3x               Launch AmnesiaDE Wayland compositor"
echo ""
echo "  DOWNLOADS:"
echo "    synth3x-downloader    Download Gentoo Stage3 / Portage"
echo ""
echo "  SYSTEM:"
echo "    reboot                Restart system"
echo "    halt                  Shutdown system"
echo "    free                  Show memory usage"
echo "    ps                    Show processes"
echo "    dmesg                 Kernel messages"
echo ""
echo " ══════════════════════════════════════════════════════════"
echo "  Run 'synth3x-installer' to start installation."
echo " ══════════════════════════════════════════════════════════"
echo ""
